config/routes.rb
Rails.application.routes.draw do
  # resources :prefectures, only: :index
  resources :prefectures, only: :index do
    get ':page', action: :index, on: :collection, as: ''
  end
  resources :addresses
  resources :users, only: [:index, :show, :new, :create] do
    collection do
      post '/confirm', to: 'users#confirm', as: :confirm
      get '/complete', to: 'users#complete', as: :complete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
  accepts_nested_attributes_for :addresses
  has_many :post_images
  accepts_nested_attributes_for :post_images

  validates :name, presence: true

  def foo
    'foo'
  end
end

app/models/user/registration_form.rb
class User::RegistrationForm
  include ActiveModel::Model
  include ActiveModel::Validations::Callbacks

  attr_accessor :user, :name, :age, :addresses, :addresses_attributes, :post_images, :post_images_attributes, :uploaded_files

  validates :name, presence: true

  def initialize(user_params = {})
    @name ||= user_params['name']
    @age ||= user_params['age']

    default_addresses = [Address.new(kind_id: 'home', prefecture_id: 13), Address.new(kind_id: 'office', prefecture_id: 13)]
    @addresses = if user_params.has_key?(:addresses_attributes)
      addresses = []
      user_params[:addresses_attributes].to_h.keys.each.with_index do |key, index|
        municipality = user_params[:addresses_attributes].to_h[key]['municipality']
        addresses << Address.new(user_params[:addresses_attributes].to_h[key]) unless municipality.blank?
      end
      if addresses.size == 0
        addresses = default_addresses
      elsif addresses.size == 1
        addresses << default_addresses.first
      end
      addresses
    else
      default_addresses
    end

    default_post_image_count = 3
    default_post_images = default_post_image_count.times.map{ PostImage.new() }
    @post_images = if user_params.has_key?(:post_images_attributes)
      images = []
      user_params[:post_images_attributes].to_h.keys.each.with_index do |key, index|
        if user_params[:post_images_attributes].to_h[key]['file_name'].kind_of?(ActionDispatch::Http::UploadedFile)
          file_name = user_params[:post_images_attributes].to_h[key]['file_name'].original_filename
          file_path = PostImage::PUBLIC_IMAGE_PATH + file_name
        else user_params[:post_images_attributes].to_h[key]['file_path'].present?
          file_path = user_params[:post_images_attributes].to_h[key]['file_path']
          file_name = file_path.gsub(PostImage::PUBLIC_IMAGE_PATH, '')
        end
        if file_path.present? && file_name.present?
          images << PostImage.new( file_name: file_name, file_path: file_path )
        end
      end

      if default_post_image_count > images.size
        (default_post_image_count - images.size).times do
          images << PostImage.new()
        end
      end
      images
    else
      default_post_images
    end

    @uploaded_files = if user_params.has_key?(:post_images_attributes)
      uploaded_files = []
      user_params[:post_images_attributes].to_h.keys.each.with_index do |key, index|
        if user_params[:post_images_attributes].to_h[key]['file_name'].present?
          uploaded_files << user_params[:post_images_attributes].to_h[key]['file_name']
        end
      end
      uploaded_files
    end
  end

  def save_image
    if @uploaded_files.present?
      @uploaded_files.each.with_index do |upload_image, index|
        output_path = Rails.root.join('public' + PostImage::PUBLIC_IMAGE_PATH, upload_image.original_filename)
        File.open(output_path, 'w+b') do |fp|
          fp.write  upload_image.read
        end
      end
    end
  end

  def save
    return false if invalid?
    @user = User.new(name: name, age: age)
    @user.addresses = @addresses
    @user.post_images = @post_images.reject{ |image| image.invalid? }
    @user.save!
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user_register_form = User::RegistrationForm.new
  end

  def confirm
    @user_register_form = User::RegistrationForm.new(user_params)
    @user_register_form.save_image
    if @user_register_form.invalid?
      render :new
    end
  end

  def create
    @user_register_form = User::RegistrationForm.new(user_params)
    if @user_register_form.save
      redirect_to complete_users_path
    else
      format.html { render :new }
    end
  end

  def complete
  end

  def edit
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user_registration_form).permit(
        :name, :age,
        addresses_attributes: [:id, :municipality, :prefecture_id, :kind_id],
        post_images_attributes: [:id, :file_name, :file_path]
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_with model: @user_register_form, url: confirm_users_path, local: true do |f|
  - if @user_register_form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_register_form.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user_register_form.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :age
    = f.number_field :age

  .field
    %ul
      = f.fields_for :addresses do |addresses_form|
        %li
          = f.label :addresses
          = addresses_form.text_field :municipality
          = addresses_form.collection_select :prefecture_id, Prefecture.all, :id, :name
          = addresses_form.select :kind_id, Address.kind_ids.keys.to_a, {}

  .field
    %ul
      = f.fields_for :post_images do |image_form|
        %li
          = f.label :post_images
          - if @user_register_form.post_images[image_form.index].file_path.nil?
            = image_form.file_field :file_name, accept: 'image/jpg,image/jpeg,image/png,image/gif'
          - else
            = image_tag @user_register_form.post_images[image_form.index].file_path, width: '100'
          = image_form.text_field :file_path

  .actions
    = f.submit 'Save'

app/views/users/complete.html.haml
%h1 complete

app/views/users/confirm.html.haml
%h1 confirm

%h2
  名前
  = @user_register_form.name

%h2
  年齢
  = @user_register_form.age

%h2
  住所
  %ul
    - @user_register_form.addresses.each do |address|
      %li= address.municipality
      %li= address.prefecture.name
      %li= address.kind_id
%h2
  画像
  %ul
    - @user_register_form.post_images.each do |post_image|
      - if post_image.file_path.present?
        %li= image_tag post_image.file_path, width: '100'

= form_with model: @user_register_form, url: users_path, local: true do |f|
  = f.hidden_field :name
  = f.hidden_field :age
  = f.fields_for :addresses do |addresses_form|
    = addresses_form.hidden_field :municipality
    = addresses_form.hidden_field :prefecture_id
    = addresses_form.hidden_field :kind_id
  = f.fields_for :post_images do |image_form|
    = image_form.hidden_field :file_name
    = image_form.hidden_field :file_path
  = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%p= link_to 'New User', new_user_path

%table
  %thead
    %tr
      %th Name
      %th Age
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.age
        %td= link_to 'Show', user

app/views/users/new.html.haml
%h1 新規ユーザー登録

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Age:
  = @user.age

%p
  %b Addresses:
  %ul
    - @user.addresses.each do |address|
      %li
        #{address.prefecture.name} #{address.municipality}（#{address.kind_id}）

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path