config/routes.rb
Rails.application.routes.draw do
  # resources :prefectures, only: :index
  resources :prefectures, only: :index do
    get ':page', action: :index, on: :collection, as: ''
  end
  resources :addresses
  resources :users, only: [:index, :show, :new, :create] do
    collection do
      post '/confirm', to: 'users#confirm', as: :confirm
      get '/complete', to: 'users#complete', as: :complete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  before_action :set_prefecture, only: [:show, :edit, :update, :destroy]

  # GET /prefectures
  # GET /prefectures.json
  def index
    @prefectures = Prefecture.page(params[:page]).per(5)
  end

  # GET /prefectures/1
  # GET /prefectures/1.json
  def show
  end

  # GET /prefectures/new
  def new
    @prefecture = Prefecture.new
  end

  # GET /prefectures/1/edit
  def edit
  end

  # POST /prefectures
  # POST /prefectures.json
  def create
    @prefecture = Prefecture.new(prefecture_params)

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully created.' }
        format.json { render :show, status: :created, location: @prefecture }
      else
        format.html { render :new }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefectures/1
  # PATCH/PUT /prefectures/1.json
  def update
    respond_to do |format|
      if @prefecture.update(prefecture_params)
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @prefecture }
      else
        format.html { render :edit }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.json
  def destroy
    @prefecture.destroy
    respond_to do |format|
      format.html { redirect_to prefectures_url, notice: 'Prefecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prefecture
      @prefecture = Prefecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prefecture_params
      params.require(:prefecture).permit(:name)
    end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/_form.html.haml
= form_for @prefecture do |f|
  - if @prefecture.errors.any?
    #error_explanation
      %h2= "#{pluralize(@prefecture.errors.count, "error")} prohibited this prefecture from being saved:"
      %ul
        - @prefecture.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/prefectures/edit.html.haml
%h1 Editing prefecture

= render 'form'

= link_to 'Show', @prefecture
\|
= link_to 'Back', prefectures_path

app/views/prefectures/index.html.haml
%h1 Listing prefectures

%table
  %thead
    %tr
      %th Name
      -# %th
      -# %th
      -# %th

  %tbody
    - @prefectures.each do |prefecture|
      %tr
        %td= prefecture.name
        -# %td= link_to 'Show', prefecture
        -# %td= link_to 'Edit', edit_prefecture_path(prefecture)
        -# %td= link_to 'Destroy', prefecture, method: :delete, data: { confirm: 'Are you sure?' }

%br

= paginate @prefectures

-# = link_to 'New Prefecture', new_prefecture_path

app/views/prefectures/new.html.haml
%h1 New prefecture

= render 'form'

= link_to 'Back', prefectures_path

app/views/prefectures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @prefecture.name

= link_to 'Edit', edit_prefecture_path(@prefecture)
\|
= link_to 'Back', prefectures_path