config/routes.rb
Rails.application.routes.draw do
  # resources :prefectures, only: :index
  resources :prefectures, only: :index do
    get ':page', action: :index, on: :collection, as: ''
  end
  resources :addresses
  resources :users, only: [:index, :show, :new, :create] do
    collection do
      post '/confirm', to: 'users#confirm', as: :confirm
      get '/complete', to: 'users#complete', as: :complete
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:user_id, :prefecture_id, :municipality, :kind_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.haml
= form_for @address do |f|
  - if @address.errors.any?
    #error_explanation
      %h2= "#{pluralize(@address.errors.count, "error")} prohibited this address from being saved:"
      %ul
        - @address.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :prefecture_id
    = f.collection_select :prefecture_id, Prefecture.all, :id, :name
  .field
    = f.label :municipality
    = f.text_field :municipality
  .field
    = f.label :kind_id
    = f.select :kind_id, Address.kind_ids.keys.to_a, {}
  .actions
    = f.submit 'Save'

app/views/addresses/edit.html.haml
%h1 Editing address

= render 'form'

= link_to 'Show', @address
\|
= link_to 'Back', addresses_path

app/views/addresses/index.html.haml
%h1 Listing addresses

%table
  %thead
    %tr
      %th User
      %th Prefecture
      %th Municipality
      %th Kind
      %th
      %th
      %th

  %tbody
    - @addresses.each do |address|
      %tr
        %td= address.user_id
        %td= address.prefecture.name
        %td= address.municipality
        %td= address.kind_id
        %td= link_to 'Show', address
        %td= link_to 'Edit', edit_address_path(address)
        %td= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Address', new_address_path

app/views/addresses/new.html.haml
%h1 New address

= render 'form'

= link_to 'Back', addresses_path

app/views/addresses/show.html.haml
%p#notice= notice

%p
  %b User:
  = @address.user_id
  = @address.user.name
%p
  %b Prefecture:
  = @address.prefecture.name
%p
  %b Municipality:
  = @address.municipality
%p
  %b Kind:
  = @address.kind_id

= link_to 'Edit', edit_address_path(@address)
\|
= link_to 'Back', addresses_path